mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=sa
    - MYSQL_PASSWORD=sa
    - MYSQL_DATABASE=db_example
    - MYSQL_RANDOM_ROOT_PASSWORD=true
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"